### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by magicsunday** [ric2016/extended_relationships#4]
Why don't host the source code at github so everyone can contribute?

**Comment by ric2016** [comment]
Short answer: Because I'm currently not a fan of git. Terrible usability, inconsistent interface ... I don't use it regularly, and therefore every time I have to, I end up spending way too much time on actions that should be trivial. Not sure it's worth the effort for a small project such as this one.

I currently don't expect a large amount of external contributions anyway. That doesn't mean I don't appreciate feedback of any kind: Any feature requests, bug reports, suggestions are very welcome!

**Comment by ric2016** [comment]
Note: The source code of all my 2.x custom modules is available directly on github:
https://github.com/vesta-webtrees-2-custom-modules

(The 1.x versions will likely not receive any substantial updates and will remain as they are, i.e. only available via the release file)
